### ISSUE TITLE
allgemeines layout

### ISSUE THREAD

**Issue by athaeck** [hfu-gis/Delta#10]

**Comment by athaeck** [comment]
textinhalt:
margin top: 2%
marin left: 26%
margin right: 26%
h1:
margin-top:2%;
margin-left: 26%;
margin-right: 26%;

**Comment by NiclasCravaack** [comment]
wir müssen noch den Hintergrund diskutieren

**Comment by NickHaecker** [comment]
h1:
margin-top:2%;
margin-left: 26%;
margin-right: 26%;
